import './style.css'
import './topics/01-tipos-basicos.ts'
import './topics/02-objetos-interfaces.ts'
import './topics/03-funciones.ts'
import './topics/04-desestructuracion.ts'
import './topics/05-desestructuracion-arrays.ts'